# job_data.py
# Diagnostics de main-d'œuvre (2024-2028)
# Source: LIS_Diagnostics_moyen_terme_2024-2028_516_professions.xlsx

JOBS = [
    {'NOC': '10', 'Title': 'Membres des corps législatifs', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '11', 'Title': 'Cadres supérieurs/cadres supérieures - administration publique', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '12', 'Title': 'Cadres supérieurs - services financiers/comm./autres', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '13', 'Title': 'Cadres supérieurs - santé/enseignement/services sociaux', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '14', 'Title': 'Cadres supérieurs - commerce/radiotélédiffusion', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '15', 'Title': 'Cadres supérieurs - construction/transports/prod.', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '10010', 'Title': 'Gestionnaires financiers/gestionnaires financières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10011', 'Title': 'Gestionnaires des ressources humaines', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10012', 'Title': 'Gestionnaires des achats', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10019', 'Title': 'Directeurs/directrices des autres services administratifs', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10020', 'Title': 'Directeurs/directrices des assurances, de l\'immobilier et du courtage financier', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10021', 'Title': 'Directeurs/directrices de banque, du crédit et d\'autres services de placements', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10022', 'Title': 'Directeurs/directrices de la publicité, du marketing et des relations publiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10029', 'Title': 'Directeurs/directrices d\'autres services aux entreprises', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '10030', 'Title': 'Directeurs/directrices des entreprises de télécommunications', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '11100', 'Title': 'Vérificateurs/vérificatrices et comptables', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '11101', 'Title': 'Analystes financiers/analystes financières et analystes en placements', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '11102', 'Title': 'Conseillers/conseillères en services financiers', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '11103', 'Title': 'Agents/agentes en valeurs, agents/agentes en placements et négociateurs/négociatrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '11109', 'Title': 'Autres agents financiers/agentes financières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '11200', 'Title': 'Professionnels/professionnelles en ressources humaines', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '11201', 'Title': 'Professionnels/professionnelles des services aux entreprises de gestion', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '11202', 'Title': 'Professionnels/professionnelles en publicité, en marketing et en relations publiques', 'Diagnosis': 'Léger surplus', 'Category': 'General / Non-Deficit'},
    {'NOC': '12010', 'Title': 'Superviseurs/superviseures de commis de bureau et du personnel de soutien administratif', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12011', 'Title': 'Superviseurs/superviseures de commis de finance et d\'assurance', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12012', 'Title': 'Superviseurs/superviseures de commis de bibliothèque, de correspondanciers et d\'autres commis à l\'information', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12013', 'Title': 'Superviseurs/superviseures des travailleurs de la chaîne d\'approvisionnement, du suivi et du calendrier de la production', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12100', 'Title': 'Adjoints administratifs/adjointes administratives', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '12101', 'Title': 'Adjoints/adjointes aux ressources humaines', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12102', 'Title': 'Agents/agentes d\'administration', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '12103', 'Title': 'Adjoints/adjointes de direction', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12110', 'Title': 'Reporters judiciaires et transcripteurs/transcriptrices médicaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12111', 'Title': 'Techniciens/techniciennes à la gestion des documents et techniciens/techniciennes en information sur la santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12112', 'Title': 'Techniciens/techniciennes aux statistiques et actuaires', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12113', 'Title': 'Estimateurs/estimatrices statistiques et chercheurs/chercheuses en statistiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12200', 'Title': 'Techniciens/techniciennes en comptabilité et teneurs/teneuses de livres', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '12201', 'Title': 'Experts/expertes en sinistres et rédacteurs/rédactrices sinistres', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12202', 'Title': 'Courtiers/courtières d\'assurances et agents/agentes d\'assurances', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '12203', 'Title': 'Évaluateurs/évaluatrices, estimateurs/estimatrices et évaluateurs-estimateurs/évaluatrices-estimatrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13100', 'Title': 'Agents/agentes d\'administration de la fonction publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13101', 'Title': 'Agents/agentes de l\'impôt, de l\'accise et du revenu', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13102', 'Title': 'Agents/agentes d\'immigration, d\'assurance-emploi et du revenu', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13110', 'Title': 'Commis aux services administratifs', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13111', 'Title': 'Commis aux services juridiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13112', 'Title': 'Courtiers/courtières en douanes, courtiers maritimes et autres', 'Diagnosis': 'Déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '13200', 'Title': 'Courtiers/courtières en douanes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '13201', 'Title': 'Coordonnateurs/coordonnatrices de la logistique de la production et du transport', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14100', 'Title': 'Employés/employées de bureau - soutien général', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14101', 'Title': 'Réceptionnistes', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14102', 'Title': 'Commis aux services du personnel', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14103', 'Title': 'Commis au tribunal et autres professions liées aux tribunaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14110', 'Title': 'Enquêteurs/enquéteuses et agents/agentes d\'entrevue et de sondage', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14111', 'Title': 'Commis à la saisie de données', 'Diagnosis': 'Léger surplus', 'Category': 'General / Non-Deficit'},
    {'NOC': '14112', 'Title': 'Commis à l\'éditique et personnel assimilé', 'Diagnosis': 'Léger surplus', 'Category': 'General / Non-Deficit'},
    {'NOC': '14200', 'Title': 'Commis à la comptabilité et personnel assimilé', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14201', 'Title': 'Commis de banque, d\'assurance et d\'autres services financiers', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14202', 'Title': 'Commis au recouvrement', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14300', 'Title': 'Commis de bibliothèque', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14301', 'Title': 'Correspondanciers/correspondancières et commis aux publications et aux règlements', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14400', 'Title': 'Expéditeurs/expéditrices et réceptionnaires', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14401', 'Title': 'Magasiniers/magasinières et commis aux pièces', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14402', 'Title': 'Commis à la production et à l\'inventaire', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14403', 'Title': 'Commis aux achats et à l\'inventaire', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '14404', 'Title': 'Répartiteurs/répartitrices et opérateurs/opératrices radio', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '14405', 'Title': 'Horairistes de trajets et d\'équipages', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '20010', 'Title': 'Gestionnaires en génie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '20011', 'Title': 'Gestionnaires des services d\'architecture et de sciences', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '20012', 'Title': 'Gestionnaires des systèmes informatiques', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21100', 'Title': 'Physiciens/physiciennes et astronomes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21101', 'Title': 'Chimistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21102', 'Title': 'Géoscientifiques et océanographes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21103', 'Title': 'Météorologues et climatologues', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21109', 'Title': 'Autres professionnels/professionnelles des sciences physiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21110', 'Title': 'Biologistes et personnel scientifique assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21111', 'Title': 'Professionnels/professionnelles des sciences forestières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21112', 'Title': 'Représentants/représentantes agricoles, experts-conseils/expertes-conseils et spécialistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21120', 'Title': 'Professionnels/professionnelles de la santé publique et de l\'environnement et de l\'hygiène et de la sécurité au travail', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21200', 'Title': 'Architectes', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21201', 'Title': 'Architectes paysagistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21202', 'Title': 'Urbanistes et planificateurs/planificatrices de l\'utilisation des sols', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21203', 'Title': 'Arpenteurs-géomètres/arpenteuses-géomètres', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21210', 'Title': 'Mathématiciens/mathématiciennes, statisticiens/statisticiennes et actuaires', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21211', 'Title': 'Scientifiques des données', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21220', 'Title': 'Spécialistes de la cybersécurité', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21221', 'Title': 'Spécialistes des systèmes commerciaux', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21222', 'Title': 'Spécialistes de l\'informatique', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21223', 'Title': 'Analystes de bases de données et administrateurs/administratrices de données', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21230', 'Title': 'Développeurs/développeuses et programmeurs/programmeuses de systèmes informatiques', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21231', 'Title': 'Ingénieurs/ingénieures et concepteurs/conceptrices en logiciel', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21232', 'Title': 'Développeurs/développeuses et programmeurs/programmeuses de logiciels', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21233', 'Title': 'Concepteurs/conceptrices Web', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21234', 'Title': 'Développeurs/développeuses et programmeurs/programmeuses Web', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21300', 'Title': 'Ingénieurs civils/ingénieures civiles', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '21301', 'Title': 'Ingénieurs mécaniciens/ingénieures mécaniciennes', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21310', 'Title': 'Ingénieurs électriques et électroniciens/ingénieures électriques et elektroniciennes', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21311', 'Title': 'Ingénieurs informaticiens/ingénieures informaticiennes (sauf ingénieurs/ingénieures et concepteurs/conceptrices en logiciel)', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21320', 'Title': 'Ingénieurs chimistes/ingénieures chimistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21321', 'Title': 'Ingénieurs industriels/ingénieures industrielles et de fabrication', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21322', 'Title': 'Ingénieurs métallurgistes et des matériaux/ingénieures métallurgistes et des matériaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21330', 'Title': 'Ingénieurs miniers/ingénieures minières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21331', 'Title': 'Ingénieurs géologues/ingénieures géologues', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21332', 'Title': 'Ingénieurs/ingénieures du pétrole', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '21390', 'Title': 'Ingénieurs/ingénieures aérospatiaux', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '21399', 'Title': 'Autres ingénieurs/ingénieures n.c.a.', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22100', 'Title': 'Technologues et techniciens/techniciennes en chimie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22101', 'Title': 'Technologues et techniciens/techniciennes en géologie et en minéralogie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22110', 'Title': 'Technologues et techniciens/techniciennes en biologie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22111', 'Title': 'Technologues et techniciens/techniciennes en sciences forestières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22112', 'Title': 'Technologues et techniciens/techniciennes en conservation et en pêche', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22113', 'Title': 'Technologues et techniciens/techniciennes en agrologie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22114', 'Title': 'Technologues et techniciens/techniciennes en architecture paysagère et en horticulture', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22210', 'Title': 'Technologues et techniciens/techniciennes en architecture', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '22211', 'Title': 'Designers industriels/designers industrielles', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22212', 'Title': 'Technologues et techniciens/techniciennes en dessin', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '22213', 'Title': 'Technologues et techniciens/techniciennes en arpentage', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22214', 'Title': 'Technologues et techniciens/techniciennes en géomatique et en météorologie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22220', 'Title': 'Technologues et techniciens/techniciennes en informatique', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22221', 'Title': 'Techniciens/techniciennes de réseau informatique et Web', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22222', 'Title': 'Agents/agentes de soutien aux utilisateurs', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22223', 'Title': 'Testeurs/testeuses de systèmes informatiques', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22230', 'Title': 'Technologues et techniciens/techniciennes en génie non destructif', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22231', 'Title': 'Technologues et techniciens/techniciennes en génie civil', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '22232', 'Title': 'Technologues et techniciens/techniciennes en génie mécanique', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22233', 'Title': 'Technologues et techniciens/techniciennes en génie industriel et en génie de fabrication', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22300', 'Title': 'Technologues et techniciens/techniciennes en génie civil', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '22301', 'Title': 'Technologues et techniciens/techniciennes en génie mécanique', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22302', 'Title': 'Technologues et techniciens/techniciennes en génie industriel et en génie de fabrication', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22303', 'Title': 'Technologues et techniciens/techniciennes en construction', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '22310', 'Title': 'Technologues et techniciens/techniciennes en génie électrique et électronique', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22311', 'Title': 'Électroniciens/électroniciennes d\'entretien (biens domestiques et commerciaux)', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '22312', 'Title': 'Techniciens/techniciennes et mécaniciens/mécaniciennes d\'instruments industriels', 'Diagnosis': 'Déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '22313', 'Title': 'Mécaniciens/mécaniciennes, techniciens/techniciennes et contrôleurs/contrôleuses d\'avionique et d\'instruments et d\'appareillages électriques d\'aéronefs', 'Diagnosis': 'Léger déficit', 'Category': 'STIM / Technologies'},
    {'NOC': '30010', 'Title': 'Gestionnaires des soins de santé', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31100', 'Title': 'Spécialistes en médecine clinique et de laboratoire', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31101', 'Title': 'Spécialistes en chirurgie', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31102', 'Title': 'Omnipraticiens/omnipraticiennes et médecins en médecine familiale', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31103', 'Title': 'Vétérinaires', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31110', 'Title': 'Dentistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31111', 'Title': 'Optométristes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31112', 'Title': 'Audiologistes et orthophonistes', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31120', 'Title': 'Pharmaciens/pharmaciennes', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31121', 'Title': 'Diététistes et nutritionnistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31200', 'Title': 'Psychologues', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31201', 'Title': 'Chiropraticiens/chiropraticiennes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31202', 'Title': 'Physiothérapeutes', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31203', 'Title': 'Ergothérapeutes', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31204', 'Title': 'Kinésiologues et autres professionnels/professionnelles en thérapie et en diagnostic', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31209', 'Title': 'Autres professionnels/professionnelles de la santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '31300', 'Title': 'Coordonnateurs/coordonnatrices et superviseurs/superviseures des soins infirmiers', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31301', 'Title': 'Infirmiers autorisés/infirmières autorisées et infirmiers psychiatriques autorisés/infirmières psychiatriques autorisées', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31302', 'Title': 'Infirmiers praticiens/infirmières praticiennes', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '31303', 'Title': 'Adjoints/adjointes au médecin, sages-femmes et professionnels/professionnelles paramédicaux', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32100', 'Title': 'Opticiens/opticiennes d\'ordonnances', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32101', 'Title': 'Infirmiers auxiliaires/infirmières auxiliaires', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32102', 'Title': 'Ambulanciers/ambulancières et paramédics', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32103', 'Title': 'Inhalothérapeutes, perfusionnistes cardiovasculaires et technologues cardiopulmonaires', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32104', 'Title': 'Technologues en santé animale et techniciens/techniciennes vétérinaires', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32109', 'Title': 'Autres technologues et techniciens/techniciennes techniques des soins de santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32110', 'Title': 'Denturologistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32111', 'Title': 'Hygiénistes et thérapeutes dentaires', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32112', 'Title': 'Technologues et techniciens/techniciennes dentaires et assistants/assistantes en laboratoire dentaire', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32120', 'Title': 'Technologues de laboratoires médicaux', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32121', 'Title': 'Technologues en radiation médicale', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32122', 'Title': 'Sonographistes médicaux/sonographistes médicales', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32123', 'Title': 'Technologues en cardiologie et technologues en électrophysiologie diagnostique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32124', 'Title': 'Techniciens/techniciennes en pharmacie', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '32129', 'Title': 'Autres technologues et techniciens/techniciennes des sciences de la santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32200', 'Title': 'Praticiens/praticiennes des médecines douces', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32201', 'Title': 'Massothérapeutes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '32209', 'Title': 'Autres praticiens/praticiennes des soins de santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '33100', 'Title': 'Assistants/assistantes dentaires et auxiliaires dans les laboratoires dentaires', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '33101', 'Title': 'Assistants/assistantes de laboratoire médical et personnel technique assimilé', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '33102', 'Title': 'Aides-infirmiers/aides-infirmières, aides-soignants/aides-soignantes et préposés/préposées aux bénéficiaires', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '33103', 'Title': 'Assistants techniques/assistantes techniques en pharmacie et assistants/assistantes en pharmacie', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '33109', 'Title': 'Autre personnel de soutien des services de santé', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '40010', 'Title': 'Directeurs/directrices des services gouvernementaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40011', 'Title': 'Cadres de la fonction publique - élaboration de politiques et administration de programmes sociaux et de santé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40012', 'Title': 'Cadres de la fonction publique - analyse économique, élaboration de politiques et administration de programmes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40013', 'Title': 'Cadres supérieurs/cadres supérieures - services sociaux, communautaires et correctionnels', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40019', 'Title': 'Cadres supérieurs/cadres supérieures - autres services', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40020', 'Title': 'Directeurs/directrices d\'école et administrateurs/administratrices de programmes d\'enseignement', 'Diagnosis': 'Léger déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '40021', 'Title': 'Directeurs/directrices de bibliothèque, des archives, de musée et de galerie d\'art', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40030', 'Title': 'Gestionnaires des services sociaux, communautaires et correctionnels', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '40040', 'Title': 'Officiers/officières de police', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40041', 'Title': 'Officiers/officières de direction des services de lutte contre les incendies', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '40042', 'Title': 'Officiers/officières des Forces armées canadiennes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41100', 'Title': 'Juges', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '41101', 'Title': 'Avocats/avocates et notaires (au Québec)', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '41200', 'Title': 'Professeurs/professeures et chargés/chargées de cours au niveau universitaire', 'Diagnosis': 'Léger déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41201', 'Title': 'Assistants/assistantes d\'enseignement et de recherche au niveau postsecondaire', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41210', 'Title': 'Enseignants/enseignantes au niveau collégial et autres instructeurs/instructrices de programmes de perfectionnement', 'Diagnosis': 'Léger déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41220', 'Title': 'Enseignants/enseignantes au niveau secondaire', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41221', 'Title': 'Enseignants/enseignantes aux niveaux primaire et préscolaire', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41300', 'Title': 'Travailleurs sociaux/travailleuses sociales', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '41301', 'Title': 'Thérapeutes conjugaux/thérapeutes conjugales, thérapeutes familiaux/thérapeutes familiales et autres conseillers assimilés/conseillères assimilées', 'Diagnosis': 'Léger déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '41302', 'Title': 'Chefs religieux/cheffes religieuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41310', 'Title': 'Enquêteurs/enquéteuses de police et autres professions policières', 'Diagnosis': 'Léger déficit', 'Category': 'Services publics / Protection'},
    {'NOC': '41311', 'Title': 'Agents/agentes de probation et de libération conditionnelle', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41320', 'Title': 'Conseillers/conseillères en éducation', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41321', 'Title': 'Conseillers/conseillères en information scolaire et professionnelle', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '41400', 'Title': 'Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en sciences naturelles et appliquées', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41401', 'Title': 'Économistes, chercheurs/chercheuses et analystes des politiques économiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41402', 'Title': 'Agents/agentes de développement économique, chercheurs/chercheuses et experts-conseils/expertes-conseils en marketing', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41403', 'Title': 'Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en politiques sociales', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '41404', 'Title': 'Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en politiques de la santé', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '41405', 'Title': 'Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en politiques de l\'éducation', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '41406', 'Title': 'Recherchistes, experts-conseils/expertes-conseils et agents/agentes de programmes, en loisirs, en sports et en conditionnement physique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '41407', 'Title': 'Officiers/officières des services de renseignements', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '41409', 'Title': 'Autres professionnels/professionnelles en sciences sociales', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '42100', 'Title': 'Policiers/policières (sauf cadres supérieurs)', 'Diagnosis': 'Léger déficit', 'Category': 'Services publics / Protection'},
    {'NOC': '42101', 'Title': 'Pompiers/pompières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '42102', 'Title': 'Membres spécialisés des Forces armées canadiennes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '42200', 'Title': 'Parajuristes et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '42201', 'Title': 'Travailleurs/travailleuses des services sociaux et communautaires', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '42202', 'Title': 'Éducateurs/éducatrices et aides-éducateurs/aides-éducatrices de la petite enfance', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '42203', 'Title': 'Instructeurs/instructrices pour personnes ayant une déficience', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '42204', 'Title': 'Travailleurs/travailleuses de la religion', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '43100', 'Title': 'Aides-enseignants/aides-enseignantes aux niveaux primaire et secondaire', 'Diagnosis': 'Déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '43109', 'Title': 'Autres instructeurs/instructrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '43200', 'Title': 'Shérifs et huissiers/huissières de justice', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '43201', 'Title': 'Agents/agentes de services correctionnels', 'Diagnosis': 'Léger déficit', 'Category': 'Services publics / Protection'},
    {'NOC': '43202', 'Title': 'Agents/agentes d\'application de règlements municipaux et autres agents/agentes de réglementation', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '43203', 'Title': 'Gardes-frontières, douaniers/douanières et agents/agentes d\'immigration', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '43204', 'Title': 'Membres des Forces armées canadiennes - opérations', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '44100', 'Title': 'Gardiens/gardiennes d\'enfants en milieu familial', 'Diagnosis': 'Léger déficit', 'Category': 'Enseignement / Éducation'},
    {'NOC': '44101', 'Title': 'Aides de maintien à domicile, aides familiaux/aides familiales et personnel assimilé', 'Diagnosis': 'Déficit', 'Category': 'Santé / Services sociaux'},
    {'NOC': '45100', 'Title': 'Élèves-officiers/élèves-officières de la marine marchande', 'Diagnosis': 'Non publié', 'Category': 'General / Non-Deficit'},
    {'NOC': '50010', 'Title': 'Directeurs/directrices de bibliothèque, des archives, de musée et de galerie d\'art', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '50011', 'Title': 'Directeurs/directrices - édition, cinéma, radiotélédiffusion et arts de la scène', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '50012', 'Title': 'Gestionnaires des programmes et des services de sports, de loisirs et de conditionnement physique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51100', 'Title': 'Bibliothécaires', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51101', 'Title': 'Conservateurs/conservatrices et restaurateurs/restauratrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51102', 'Title': 'Archivistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51110', 'Title': 'Rédacteurs/rédactrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51111', 'Title': 'Auteurs/auteures, écrivains/écrivaines et rédacteurs/rédactrices', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51112', 'Title': 'Rédacteurs techniques/rédactrices techniques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51113', 'Title': 'Journalistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51114', 'Title': 'Traducteurs/traductrices, terminologues et interprètes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51120', 'Title': 'Producteurs/productrices, réalisateurs/réalisatrices, chorégraphes et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51121', 'Title': 'Chefs d\'orchestre, compositeurs/compositrices et arrangeurs/arrangeuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '51122', 'Title': 'Musiciens/musiciennes et chanteurs/chanteuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52100', 'Title': 'Techniciens/techniciennes en bibliothéconomie et en administration publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52110', 'Title': 'Cadreurs/cadreuses de films et vidéos', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52111', 'Title': 'Techniciens/techniciennes en graphisme', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '52112', 'Title': 'Techniciens/techniciennes en radiotélédiffusion', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52113', 'Title': 'Techniciens/techniciennes en enregistrement audio et vidéo', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52114', 'Title': 'Annonceurs/annonceuses et autres radiodiffuseurs/autres radiodiffuseuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52119', 'Title': 'Autres techniciens/techniciennes et personnel de coordination du cinéma, de la radiotélédiffusion et des arts de la scène', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '52120', 'Title': 'Designers graphiques et illustrateurs/illustratrices', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '52121', 'Title': 'Designers d\'intérieur et décorateurs/décoratrices d\'intérieur', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53100', 'Title': 'Registraires, restaurateurs/restauratrices, interprètes et autres travailleurs/travailleuses du domaine des musées et des galeries d\'art', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53110', 'Title': 'Photographes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53111', 'Title': 'Ensembliers/ensemblières de théâtre, dessinateurs/dessinatrices de mode, concepteurs/conceptrices d\'expositions et autres concepteurs/conceptrices artistiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53120', 'Title': 'Danseurs/danseuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53121', 'Title': 'Acteurs/actrices et comédiens/comédiennes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53122', 'Title': 'Peintres, sculpteurs/sculpteures et autres artistes des arts visuels', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53123', 'Title': 'Artisans/artisanes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53124', 'Title': 'Concepteurs/conceptrices de modèles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53125', 'Title': 'Autre personnel technique et de coordination du cinéma, de la radiotélédiffusion et des arts de la scène', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53200', 'Title': 'Animateurs/animatrices et responsables de programmes de sports, de loisirs et de conditionnement physique', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '53201', 'Title': 'Athlètes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53202', 'Title': 'Entraîneurs/entraîneuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '53203', 'Title': 'Arbitres et officiels/officielles de sports', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '54100', 'Title': 'Assistants/assistantes de bibliothèque et commis', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '55109', 'Title': 'Autres artistes de spectacle n.c.a.', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '60010', 'Title': 'Directeurs/directrices des ventes corporatives', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '60020', 'Title': 'Directeurs/directrices - commerce de détail et de gros', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '60030', 'Title': 'Directeurs/directrices de la restauration et des services alimentaires', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '60031', 'Title': 'Directeurs/directrices des services d\'hébergement', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '60040', 'Title': 'Directeurs/directrices du service à la clientèle et des services personnels, n.c.a.', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '62010', 'Title': 'Superviseurs/superviseures des ventes - commerce de détail', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '62020', 'Title': 'Superviseurs/superviseures des services alimentaires', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '62021', 'Title': 'Chefs', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '62022', 'Title': 'Superviseurs/superviseures des services d\'hébergement, de voyages, de tourisme et de services connexes', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '62023', 'Title': 'Superviseurs/superviseures des services à la clientèle et de l\'information', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '62024', 'Title': 'Superviseurs/superviseures des services de nettoyage', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '62029', 'Title': 'Superviseurs/superviseures des autres services', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '62100', 'Title': 'Spécialistes des ventes techniques - commerce de gros', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '62101', 'Title': 'Acheteurs/acheteuses des commerces de détail et de gros', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '62200', 'Title': 'Chefs et cuisiniers/cuisinières spécialisés', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '62201', 'Title': 'Directeurs/directrices de funérailles et embaumeurs/embaumeuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '62202', 'Title': 'Agents/agentes de voyages', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63100', 'Title': 'Agents/agentes et courtiers/courtières d\'assurance', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63101', 'Title': 'Agents/agentes et courtiers/courtières d\'immeubles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63102', 'Title': 'Vendeurs/vendeuses - services financiers', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63200', 'Title': 'Cuisiniers/cuisinières', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '63201', 'Title': 'Bouchers/bouchères, coupeurs/coupeuses de viande et poissonniers/poissonnières - commerce de gros et de détail', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '63202', 'Title': 'Boulangers-pâtissiers/boulangères-pâtissières', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '63210', 'Title': 'Coiffeurs/coiffeuses et barbiers', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '63211', 'Title': 'Esthéticiens/esthéticiennes, électrolystes et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63220', 'Title': 'Cordonniers/cordonnières et fabricants/fabricantes de chaussures', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '63221', 'Title': 'Tapissiers-garnisseurs/tapissières-garnisseuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64100', 'Title': 'Vendeurs/vendeuses et décorateurs-étalagistes/décoratrices-étalagistes en commerce de détail', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '64101', 'Title': 'Représentants/représentantes des ventes et des comptes - commerce de gros (non-technique)', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '64200', 'Title': 'Tailleurs/tailleuses, couturiers/couturières, fourreurs/fourreuses et modistes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64201', 'Title': 'Personnel de soutien en services de funérailles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64300', 'Title': 'Maîtres d\'hôtel et hôtes/hôtesses', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '64301', 'Title': 'Barmans/barmaids', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '64310', 'Title': 'Guides touristiques et de voyages', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64311', 'Title': 'Guides d\'activités récréatives et sportives de plein air', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64312', 'Title': 'Autre personnel des services de l\'hébergement, des voyages et du tourisme', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64313', 'Title': 'Personnel ambulant des services de divertissement et des loisirs', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64314', 'Title': 'Personnel de services de soutien dans les hôtels', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '64320', 'Title': 'Opérateurs/opératrices des services de tourisme, de voyages et de guides', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64321', 'Title': 'Croupiers/croupières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64322', 'Title': 'Préposés/préposées aux jeux et aux divertissements', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64400', 'Title': 'Représentants/représentantes au service à la clientèle - institutions financières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64401', 'Title': 'Représentants/représentantes au service postal', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64409', 'Title': 'Autres représentants/représentantes au service à la clientèle et préposés/préposées aux renseignements', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '64410', 'Title': 'Agents/agentes de sécurité et personnel assimilé des services de sécurité', 'Diagnosis': 'Léger déficit', 'Category': 'Services publics / Protection'},
    {'NOC': '65100', 'Title': 'Caissiers/caissières', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65101', 'Title': 'Préposés/préposées de stations-service', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '65102', 'Title': 'Garnisseurs/garnisseuses de tablettes, commis et préposés/préposées aux commandes dans les magasins', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65109', 'Title': 'Autres préposés/préposées aux ventes et aux services', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65200', 'Title': 'Serveurs/serveuses au comptoir, aides de cuisine et personnel de soutien assimilé', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '65201', 'Title': 'Serveurs/serveuses d\'aliments et de boissons', 'Diagnosis': 'Déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '65202', 'Title': 'Coupeurs/coupeuses de viande et poissonniers/poissonnières - commerce de gros et de détail', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '65210', 'Title': 'Personnel de soutien en services d\'hébergement, de voyages et de tourisme', 'Diagnosis': 'Léger déficit', 'Category': 'Tourisme / Hôtellerie'},
    {'NOC': '65211', 'Title': 'Opérateurs/opératrices et préposés/préposées aux sports, aux loisirs et dans les parcs d\'attractions', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '65220', 'Title': 'Nettoyeurs/nettoyeuses spécialisés', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65229', 'Title': 'Autres préposés/préposées aux services d\'information et aux services à la clientèle', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '65310', 'Title': 'Préposés/préposées à l\'entretien ménager et au nettoyage - travaux légers', 'Diagnosis': 'Déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65311', 'Title': 'Nettoyeurs/nettoyeuses spécialisés', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '65312', 'Title': 'Concierges et surintendants/surintendantes d\'immeubles', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '65320', 'Title': 'Nettoyeurs/nettoyeuses à sec, blanchisseurs/blanchisseuses et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '65329', 'Title': 'Autres préposés/préposées aux services n.c.a.', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '70010', 'Title': 'Gestionnaires de la construction', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '70011', 'Title': 'Gestionnaires de la construction et rénovation résidentielle', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '70012', 'Title': 'Gestionnaires de l\'exploitation et de l\'entretien d\'immeubles', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '70020', 'Title': 'Gestionnaires en transport', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '70021', 'Title': 'Gestionnaires des services postaux et de messagerie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72010', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des machinistes et du personnel de formage, de profilage et de montage des métaux', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72011', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en électricité et en télécommunications', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72012', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en tuyauterie', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72013', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en charpenterie', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72014', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des autres métiers de la construction et des services de réparation et d\'installation', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72020', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses en mécanique', 'Diagnosis': 'Déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72021', 'Title': 'Entrepreneurs/entrepreneuses et contremaîtres/contremaîtresses des équipes d\'opérateurs d\'équipement lourd', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72022', 'Title': 'Superviseurs/superviseures de l\'imprimerie et du personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72023', 'Title': 'Superviseurs/superviseures des opérations du transport ferroviaire', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72024', 'Title': 'Superviseurs/superviseures du transport routier et du transport en commun', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72100', 'Title': 'Machinistes et vérificateurs/vérificatrices d\'usinage et d\'outillage', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72101', 'Title': 'Outilleurs-ajusteurs/outilleuses-ajusteuses', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72102', 'Title': 'Tôliers/tôlières', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72103', 'Title': 'Chaudronniers/chaudronnières', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72104', 'Title': 'Charpentiers-menuisiers/charpentières-menuisières', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72105', 'Title': 'Poseurs/poseuses de revêtements d\'intérieur', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72106', 'Title': 'Soudeurs/soudeuses et opérateurs/opératrices de machines à souder et à braser', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72200', 'Title': 'Électriciens/électriciennes (sauf électriciens industriels/électriciennes industrielles et de réseaux électriques)', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72201', 'Title': 'Électriciens industriels/électriciennes industrielles', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72202', 'Title': 'Électriciens/électriciennes de réseaux électriques', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72203', 'Title': 'Monteurs/monteuses de lignes électriques et de câbles', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72204', 'Title': 'Installateurs/installatrices et réparateurs/réparatrices de matériel de télécommunications', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72205', 'Title': 'Techniciens/techniciennes en câblodistribution et en entretien de circuits', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72300', 'Title': 'Plombiers/plombières', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72301', 'Title': 'Tuyauteurs/tuyauteuses, monteurs/monteuses de tuyaux à vapeur et poseurs/poseuses de gicleurs', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72302', 'Title': 'Mécaniciens/mécaniciennes en chauffage, réfrigération et climatisation', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72310', 'Title': 'Charpentiers-menuisiers/charpentières-menuisières', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72311', 'Title': 'Ébénistes', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72320', 'Title': 'Maçons/maçonnes', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72321', 'Title': 'Finisseurs/finisseuses de béton', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72322', 'Title': 'Carreleurs/carreleuses', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72323', 'Title': 'Plâtriers/plâtrières, poseurs/poseuses de systèmes intérieurs et finisseurs/finisseuses de systèmes intérieurs', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72324', 'Title': 'Couvreurs/couvreuses et poseurs/poseuses de bardeaux', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72325', 'Title': 'Vitriers/vitrières', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72326', 'Title': 'Peintres et décorateurs/décoratrices (sauf décorateurs/décoratrices d\'intérieur)', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72327', 'Title': 'Poseurs/poseuses de revêtements de sol', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72328', 'Title': 'Calorifugeurs/calorifugeuses', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72400', 'Title': 'Mécaniciens/mécaniciennes de chantier et mécaniciens industriels/mécaniciennes industrielles', 'Diagnosis': 'Déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72401', 'Title': 'Mécaniciens/mécaniciennes d\'équipement lourd', 'Diagnosis': 'Déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72402', 'Title': 'Mécaniciens/mécaniciennes en réfrigération et en climatisation', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72403', 'Title': 'Réparateurs/réparatrices de wagons', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72404', 'Title': 'Mécaniciens/mécaniciennes d\'aéronefs et contrôleurs/contrôleuses d\'aéronefs', 'Diagnosis': 'Léger déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72405', 'Title': 'Mécaniciens/mécaniciennes de machines fixes et opérateurs/opératrices de machines auxiliaires', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72406', 'Title': 'Constructeurs/constructrices et mécaniciens/mécaniciennes d\'ascenseurs', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72410', 'Title': 'Mécaniciens/mécaniciennes et réparateurs/réparatrices de véhicules automobiles, de camions et d\'autobus', 'Diagnosis': 'Déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72411', 'Title': 'Débosseleurs/débosseleuses et réparateurs/réparatrices de carrosserie', 'Diagnosis': 'Déficit', 'Category': 'Mécanique / Transport'},
    {'NOC': '72420', 'Title': 'Mécaniciens/mécaniciennes en chauffage, réfrigération et climatisation', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72421', 'Title': 'Réparateurs/réparatrices d\'appareils électroménagers', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72422', 'Title': 'Électromécaniciens/électromécaniciennes', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '72423', 'Title': 'Réparateurs/réparatrices de moteurs électriques et de transformateurs', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72429', 'Title': 'Autres réparateurs/réparatrices de petits moteurs et d\'équipements', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72500', 'Title': 'Grutiers/grutières', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '72501', 'Title': 'Foreurs/foreuses de puits d\'eau', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72600', 'Title': 'Pilotes, navigateurs/navigatrices et instructeurs/instructrices de pilotage du transport aérien', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72601', 'Title': 'Contrôleurs aériens/contrôleuses aériennes et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72602', 'Title': 'Officiers/officières de pont du transport par voies navigables', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72603', 'Title': 'Officiers mécaniciens/officières mécaniciennes du transport par voies navigables', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '72604', 'Title': 'Contrôleurs/contrôleuses de la circulation ferroviaire et régulateurs/régulatrices de la circulation maritime', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '72999', 'Title': 'Autres métiers techniques et personnel assimilé', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73100', 'Title': 'Ouvriers/ouvrières agricoles', 'Diagnosis': 'Déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '73101', 'Title': 'Ouvriers/ouvrières de l\'aménagement paysager et de l\'entretien des terrains', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '73102', 'Title': 'Ouvriers/ouvrières de pépinières et de serres', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73110', 'Title': 'Opérateurs/opératrices de machinerie lourde (sauf grutiers/grutières)', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '73111', 'Title': 'Opérateurs/opératrices de machines d\'abattage d\'arbres', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '73112', 'Title': 'Ouvriers/ouvrières de l\'exploitation forestière', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73113', 'Title': 'Ouvriers/ouvrières de scieries', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73200', 'Title': 'Ouvriers/ouvrières à la construction', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '73201', 'Title': 'Manoeuvres en construction', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '73300', 'Title': 'Conducteurs/conductrices de camions de transport', 'Diagnosis': 'Déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '73301', 'Title': 'Conducteurs/conductrices d\'autobus, opérateurs/opératrices de métro et autres opérateurs/opératrices de transport en commun', 'Diagnosis': 'Déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '73310', 'Title': 'Mécaniciens/mécaniciennes de locomotive et de cour de triage', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73311', 'Title': 'Chefs de train et serre-freins', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '73400', 'Title': 'Matelots de pont et matelots de salle des machines', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '73401', 'Title': 'Ouvriers/ouvrières de manutention', 'Diagnosis': 'Léger déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '73402', 'Title': 'Foreurs/foreuses et dynamiteurs/dynamiteuses de mines à ciel ouvert, de carrières et de chantiers de construction', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '74100', 'Title': 'Installateurs/installatrices et réparateurs/réparatrices de matériel de télécommunications', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '74101', 'Title': 'Monteurs/monteuses de lignes et de câbles de télécommunications', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '74102', 'Title': 'Installateurs/installatrices et réparateurs/réparatrices de matériel électronique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '74200', 'Title': 'Monteurs/monteuses de charpentes métalliques', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '74201', 'Title': 'Monteurs/monteuses de lignes électriques et de câbles', 'Diagnosis': 'Déficit', 'Category': 'Construction / BTP'},
    {'NOC': '74202', 'Title': 'Monteurs/monteuses de pipelines, de conduites de gaz et de câbles de télécommunications', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '74203', 'Title': 'Foreurs/foreuses de puits de pétrole et de gaz, de sondage et de services connexes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '74204', 'Title': 'Ouvriers/ouvrières de l\'extraction et du raffinage du pétrole et du gaz', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '74205', 'Title': 'Foreurs/foreuses et dynamiteurs/dynamiteuses de mines à ciel ouvert, de carrières et de chantiers de construction', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '75100', 'Title': 'Débardeurs/débardeurs', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '75101', 'Title': 'Manutentionnaires', 'Diagnosis': 'Déficit', 'Category': 'Services professionnels / logistique'},
    {'NOC': '75110', 'Title': 'Ouvriers/ouvrières dans le traitement des minerais et du métal', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '75111', 'Title': 'Ouvriers/ouvrières dans le traitement des pâtes et papiers et du bois', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '75119', 'Title': 'Autres ouvriers/ouvrières dans le traitement et la fabrication', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '80010', 'Title': 'Gestionnaires de l\'exploitation des ressources naturelles et de la pêche', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '80020', 'Title': 'Gestionnaires en agriculture, en horticulture et en aquaculture', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '80021', 'Title': 'Gestionnaires en aménagement paysager et en entretien des terrains', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '82010', 'Title': 'Superviseurs/superviseures de l\'exploitation forestière', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '82020', 'Title': 'Superviseurs/superviseures de l\'exploitation minière et des carrières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '82021', 'Title': 'Superviseurs/superviseures du forage et des services reliés à l\'extraction de pétrole et de gaz', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '82030', 'Title': 'Entrepreneurs/entrepreneuses de services agricoles, surveillants/surveillantes d\'exploitations agricoles et ouvriers spécialisés/ouvrières spécialisées dans l\'élevage', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '82031', 'Title': 'Entrepreneurs/entrepreneuses et superviseurs/superviseures de l\'aménagement paysager, de l\'entretien des terrains et de l\'horticulture', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '83100', 'Title': 'Mineurs/mineuses d\'extraction et de préparation, mines souterraines', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '83101', 'Title': 'Foreurs/foreuses de puits de pétrole et de gaz, de sondage et de services connexes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '83110', 'Title': 'Ouvriers/ouvrières de l\'exploitation forestière', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '83120', 'Title': 'Pêcheurs indépendants/pêcheuses indépendantes', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '83121', 'Title': 'Pêcheurs/pêcheuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '84100', 'Title': 'Ouvriers/ouvrières de l\'exploitation minière souterraine et de l\'aménagement', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '84101', 'Title': 'Ouvriers/ouvrières de l\'extraction et du raffinage du pétrole et du gaz', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '84120', 'Title': 'Ouvriers/ouvrières de l\'exploitation forestière et de la sylviculture', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '84121', 'Title': 'Ouvriers/ouvrières agricoles', 'Diagnosis': 'Déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '85100', 'Title': 'Ouvriers/ouvrières dans l\'élevage et travailleurs/travailleuses de soins aux animaux', 'Diagnosis': 'Léger déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '85101', 'Title': 'Ouvriers/ouvrières à la récolte', 'Diagnosis': 'Déficit', 'Category': 'Ressources naturelles / Agriculture'},
    {'NOC': '85102', 'Title': 'Ouvriers/ouvrières de l\'aquaculture et de la mariculture', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '85103', 'Title': 'Ouvriers/ouvrières de pépinières et de serres', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '85110', 'Title': 'Trappeurs/trappeuses et chasseurs/chasseuses', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '85120', 'Title': 'Ouvriers/ouvrières sylvicoles et forestiers/forestières', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '85121', 'Title': 'Ouvriers/ouvrières d\'aménagement paysager et d\'entretien de terrains', 'Diagnosis': 'Léger déficit', 'Category': 'Construction / BTP'},
    {'NOC': '90010', 'Title': 'Directeurs/directrices de la fabrication', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '90011', 'Title': 'Directeurs/directrices des services d\'utilité publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92010', 'Title': 'Surveillants/surveillantes dans la transformation des métaux et des minerais', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '92011', 'Title': 'Surveillants/surveillantes dans le raffinage du pétrole, le traitement du gaz et des produits chimiques et les services d\'utilité publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92012', 'Title': 'Surveillants/surveillantes dans la transformation des aliments, des boissons et du tabac', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '92013', 'Title': 'Surveillants/surveillantes dans la fabrication de produits en plastique et en caoutchouc', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '92014', 'Title': 'Surveillants/surveillantes dans la transformation des produits forestiers', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92015', 'Title': 'Surveillants/surveillantes dans la transformation et la fabrication de produits textiles, de tissus, de fourrure et de cuir', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92020', 'Title': 'Surveillants/surveillantes dans l\'assemblage de véhicules automobiles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92021', 'Title': 'Surveillants/surveillantes dans la fabrication de produits électroniques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92022', 'Title': 'Surveillants/surveillantes dans la fabrication de produits électriques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92023', 'Title': 'Surveillants/surveillantes dans la fabrication de meubles et d\'accessoires', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '92024', 'Title': 'Surveillants/surveillantes dans la fabrication d\'autres produits métalliques et de pièces mécaniques', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '92100', 'Title': 'Opérateurs/opératrices de poste central de contrôle et de conduite de procédés industriels dans le traitement des métaux et des minerais', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '92101', 'Title': 'Opérateurs/opératrices d\'installations de traitement des produits chimiques et opérateurs/opératrices de machines de traitement des matières plastiques', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93100', 'Title': 'Opérateurs/opératrices de machines dans le traitement des métaux et des minerais', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93101', 'Title': 'Opérateurs/opératrices de machines de traitement des métaux lourds', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93102', 'Title': 'Opérateurs/opératrices de machines de formage des métaux', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93200', 'Title': 'Opérateurs/opératrices de machines à assembler, à ajuster et à contrôler les aéronefs', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93201', 'Title': 'Monteurs/monteuses d\'aéronefs', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '93202', 'Title': 'Monteurs/monteuses de véhicules automobiles, de camionnettes et d\'autobus', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '93203', 'Title': 'Monteurs/monteuses de matériel électrique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94100', 'Title': 'Opérateurs/opératrices de machines et de procédés industriels dans le traitement des aliments, des boissons et des produits connexes', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94101', 'Title': 'Bouchers industriels/bouchères industrielles, dépeceurs-découpeurs/dépeceuses-découpeuses de viande, préparateurs/préparatrices de volaille et personnel assimilé', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94102', 'Title': 'Opérateurs/opératrices de machines de transformation du poisson et de fruits de mer', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94103', 'Title': 'Testeurs/testeuses et classeurs/classeuses dans la transformation des aliments et des boissons', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94104', 'Title': 'Ouvriers/ouvrières dans la transformation des aliments et des boissons', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94105', 'Title': 'Opérateurs/opératrices de machines à coudre industrielle', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94106', 'Title': 'Opérateurs/opératrices de machines de traitement des textiles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94107', 'Title': 'Opérateurs/opératrices de machines de traitement et de finition des produits textiles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94110', 'Title': 'Opérateurs/opératrices de machines à imprimer', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94111', 'Title': 'Opérateurs/opératrices de machines à relier et de finition', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94112', 'Title': 'Opérateurs/opératrices de matériel de développement de films et de photographies', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94120', 'Title': 'Opérateurs/opératrices de machines à scier dans les scieries', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94121', 'Title': 'Opérateurs/opératrices de machines à travailler le bois', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94122', 'Title': 'Opérateurs/opératrices de machines de traitement des pâtes et papiers et du bois', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94123', 'Title': 'Classeurs/classeuses de bois d\'oeuvre et d\'autres produits du bois', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94130', 'Title': 'Opérateurs/opératrices de machines d\'usinage du plastique', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94131', 'Title': 'Opérateurs/opératrices de machines de traitement des produits en caoutchouc', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94132', 'Title': 'Opérateurs/opératrices de machines de fabrication de produits en plastique', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94140', 'Title': 'Opérateurs/opératrices de machines de traitement des produits chimiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94141', 'Title': 'Opérateurs/opératrices de machines de traitement du pétrole, du gaz et des produits chimiques', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94142', 'Title': 'Opérateurs/opératrices de machines de traitement de l\'eau et des déchets', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94143', 'Title': 'Opérateurs/opératrices d\'installations de traitement des eaux et des déchets', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94150', 'Title': 'Opérateurs/opératrices de machines de traitement des minéraux et des métaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94151', 'Title': 'Opérateurs/opératrices de machines de fonderie', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94152', 'Title': 'Ouvriers/ouvrières de la fabrication du verre', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94153', 'Title': 'Opérateurs/opératrices de machines de fabrication de produits en béton, en argile et en pierre', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94154', 'Title': 'Inspecteurs/inspectrices et contrôleurs/contrôleuses dans la transformation des minéraux et des métaux', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94200', 'Title': 'Assembleurs/assembleuses et contrôleurs/contrôleuses de véhicules automobiles', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94201', 'Title': 'Assembleurs/assembleuses, finisseurs/finisseuses et contrôleurs/contrôleuses de produits en électronique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94202', 'Title': 'Assembleurs/assembleuses et contrôleurs/contrôleuses de matériel électrique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94203', 'Title': 'Assembleurs/assembleuses, finisseurs/finisseuses et contrôleurs/contrôleuses de produits divers', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94204', 'Title': 'Monteurs/monteuses de produits mécaniques', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94210', 'Title': 'Monteurs/monteuses de meubles et d\'accessoires', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94211', 'Title': 'Assembleurs/assembleuses et contrôleurs/contrôleuses de matériel de sport, de jeux et de jouets', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '94212', 'Title': 'Autres assembleurs/assembleuses et contrôleurs/contrôleuses', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94213', 'Title': 'Peintres et enduiseurs/enduiseuses industriels', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '94219', 'Title': 'Autres opérateurs/opératrices de machines et personnel assimilé dans la fabrication', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '95100', 'Title': 'Ouvriers/ouvrières dans le traitement des métaux et des minerais', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '95101', 'Title': 'Ouvriers/ouvrières dans la fabrication de produits métalliques', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '95102', 'Title': 'Ouvriers/ouvrières dans la fabrication de produits chimiques et le traitement des services d\'utilité publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '95103', 'Title': 'Ouvriers/ouvrières dans le traitement du bois, des pâtes et papiers', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '95104', 'Title': 'Ouvriers/ouvrières dans la fabrication de produits en caoutchouc et en plastique', 'Diagnosis': 'Léger déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '95105', 'Title': 'Ouvriers/ouvrières dans la fabrication de produits textiles, de tissus, de fourrure et de cuir', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '95106', 'Title': 'Ouvriers/ouvrières dans la transformation des aliments, des boissons et du tabac', 'Diagnosis': 'Déficit', 'Category': 'Fabrication / Métallurgie'},
    {'NOC': '95107', 'Title': 'Ouvriers/ouvrières dans la fabrication de produits en béton, en argile et en pierre', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'},
    {'NOC': '95109', 'Title': 'Autres ouvriers/ouvrières dans la fabrication et les services d\'utilité publique', 'Diagnosis': 'Équilibré', 'Category': 'General / Non-Deficit'}
]
